let language =
[
	{
		// 登录部份-------简体中文
	 language1:"登入Cat",
	 language2:"请填写正确格式",
	 language3:"下一步",
	 language4:"将向您发送 One Click 登录的验证邮件",
	 language5:"验证码已发送",
	 language6:"已发送到",
	 language7:"请确认你的电子信箱，并输入六位数代码！",
	 language8:"6位数代码！",
	 language9:"若确认未收到信，请检查垃圾信件或 在1:57 之后重新发送验证电子邮件",
	 language10:"电子邮件验证失败",
	 language11:"若确认未收到信，请检查垃圾信件或",
	 language12:"重新发送验证信",
	 language13:"若确认未收到信，请检查垃圾信件或 在1:57 之后重新发送验证电子邮件",
	 language14:"欢迎来到亚洲最大的私密成人平台 我们能给你的以一切叫做爱",
	 language15:"使用电子邮件登入/注册",
	 language16:"其他登录方法",
	 language17:"注册/登入即代表你年满18岁并同意",
	 language18:"电子邮件",
	 language19:"将向您发送 One Click 登录的验证邮件",
	 language20:"请输入手机号",
	 language21:"验证码将传送到你的手机",
	 language22:"您的电话号码",
	 language23:"接收验证码",
	 language24:"选择国家",
	 language25:"搜索",
	 language26:"号码格式不符",
	 language27:"输入验证码",
	 language28:"已传送短信验证码到",
	 language29:"17秒",
	 language30:"修改手机号",
	 language31:"无效验证码",
	 
	 // 购买金币部分
	 language32:"购买金币",
	 language33:"购买包月VIP可享专属服务",
	 language34:"详情",
	 language35:"选择货币",
	 language36:"包月",
	 language37:"特权一",
	 language38:"免费获得XXXXXX金币",
	 language39:"特权二",
	 language40:"免费获得XXXXXX金币",
	 language41:"我要包月",
	 language42:"说明",
	 language43:"包月vip服务声明",
	 language44:"付款:用户确认购买绑定付款方式",
	 language45:"包月vip服务声明  付款：用户确认购买绑定付款方式  取消包月：如需取消包月，请在当前包月周期到期前24小时以 前，手动取消 个人中心-设置-付款方式绑定中取消,到期前24小时以内取消，将会收取包月费用。",
	 language46:"包月:包月周期前24小时内进行扣款,扣款成功后包月周期顺延一个包月周期。",
	 language47:"我要包月",
	 
	 
	 
	 language48:"首頁",
	 language49:"解鎖",
	 language50:"更多",
	 language51:"总排行榜",
	 language52:"解锁榜",
	 language53:"聊天榜",
	 language54:"礼物榜",
	 language55:"搜索",
	 language56:"群发影片",
	 language57:"标签",
	 language58:"Swagger",
	 language59:"热门搜索",
	 language60:"最近",
	 language61:"粉丝推荐",
	 language62:"关注中",
	 language63:"粉丝",
	 language64:"编辑",
	 language65:"已买商品",
	 language66:"贴文", // 删除 数字内容
	 language67:"保存",
	 language68:"用户名",
	 language69:"用户说明",
	 language70:"档案信息编辑",
	 language71:"关注",
	 language72:"在线",
	 language73:"热门",
	 language74:"全球榜",
	 language75:"送礼",
	 language76:"聊天",
	 language77:"大家都在看",
	 language78:"解锁",
	 language79:"新帖子",
	 language80:"性感",
	 language81:"则帖子",
	 language82:"所有信息",
	 language83:"剩余47小时",
	 language84:"取消",
	 language85:"免费",
	 language86:"商品管理",
	 language87:"收益管理",
	 language88:"已过期",
	 language89:"未审核",
	 language90:"删除",
	 language91:"编辑",
	 language93:"上传作品",
	 language94:"名称",
	 language95:"价格",
	 language96:"上传",
	 language97:"图片",
	 language98:"时效",
	 language99:"提交",
	 language100:"收益管理",
	 language101:"私讯",
	 language102:"购买了你的视频",
	 language103:"给你发了一条私讯",
	 language104:"购买金币",
	 language105:"信用卡支付",
	 language106:"您的卡片资料完全由合作金流进行加密处理；Cat不会保留完整的卡 号信息。",
	 language107:"信用卡支付",
	 language108:"超商",
	 language109:"ibon便利生活站",
	 language110:"全家FAMIPORT",
	 language111:"ATM",
	 language112:"信用卡支付",
	 language113:"24小时",
	 language114:"7日",
	 language115:"30日",
	 language116:"每小时更新一次",
	 language117:"每日更新一次",
	 language118:"设定",
	 language119:"个人",
	 language120:"探索页喜好",
	 language121:"女性",
	 language122:"已连结账号",
	 language123:"封锁名单",
	 language124:"删除账号",
	 language125:"钱包",
	 language126:"日志",
	 language127:"支付方式",
	 language128:"我的电子收据",
	 language129:"购买金币",
	 language130:"关于",
	 language131:"语言",
	 language132:"简体中文",
	 language133:"繁体中文",
	 language134:"英语",
	 language135:"泰文",
	 language136:"男性",
	 language137:"全部",
	 language138:"常见问题",
	 language139:"联系客服",
	 language140:"系统问题反馈",
	 language141:"免费下载 catr 应用程序",
	 language142:"更多",
	 language143:"退出",
	 language144:"我的电子收据",
	 language145:"捐赠发票",
	 language146:"电子收据",
	 language147:"探索页喜好",
	 language148:"已连结账号",
	 language149:"电子邮件",
	 language150:"Google",
	 language151:"Facebook",
	 language152:"Twitter",
	 language153:"line",
	 language154:"电话号码",
	 language155:"连结账号",
	 language156:"日志",
	 language157:"所有",
	 language158:"获得金币",
	 language159:"登录奖励",
	 language160:"用户充值",
	 language161:"礼物赠送",
	 language162:"个人设定",
	 language163:"请输入您的用户名",
	 language164:"限20字内，使用者名称仅可使用小写字母、数字",
	 language165:"Oops!您的年龄无法承受这些刺激",
	 language166:"你感兴趣的对象是...",
	 language167:"可复选，若欲更改至设定页改变设定",
	 language168:"同意接收Cat的最新消息",
	 language169:"完成",
	 language170:"删除账号",
	 language171:"如果您想要删除Cat账号，请输入账号用户名确认正确。删除程序一旦 开始，您将无法重启账号获取过去加到账号的任何内容或资料。",
	 language172:"请输入您的用户名称",
	 language173:"确认",
	 
	 //聊天
	 language174:"选择朋友",
	 language175:"搜索",
	 language176:"我的朋友",
	 language177:"聊天",
	 language178:"建立聊天室",
	 language179:"跟对方说声嗨！ 开始你们的 1 对 1 聊天",
	 language180:"以3500 传送信息",
	 language181:"拍照",
	 language182:"上传",
	 language183:"作品列表",
	 language184:"应援",
	 language185:"情趣用品",
	 language186:"角色扮演",
	 language187:"生日快乐",
	 language188:"漂亮宝贝",
	 language189:"封锁名单",
	 language191:"解除封锁",
	 language192:"关于我",
	 language193:"106字",
	 language194:"作品列表",
	 language195:"取消",
	 language196:"推播通知",
	 language197:"私讯通知",
	 
	 language198:"登录/注册",
	 language199:"条款",
	 language200:"在",
	 language201:"之后重新发送验证电子邮件",
	 language202:"金币",
	 language203:"视频",
	 language204:"选择上传",
	 language205:"小时",
	 language206:"标签前需要加#号区分",
	 language207:"剩余",
	 language208:"小时",
	 language209:"分钟",
	 language210:"秒",
	 language211:"拉黑",
	 language212:"跟对方说声嗨！",
	 language213:"开始你们的 1 对 1 聊天",
	 language214:"客服LINE",
	 language215:"消费明细",
	 language216:"观看",
	 language217:"绑定邮箱",
	 language218:"账号不能为空",
	 language219:"可以注册",
	 language220:"账号已存在",
	 language221:"私讯价格",
	 language222:"合计收益",
	 language223:"热门主播",
	 language224:"的限时动态",
	 language225:"相机",
	 language226:"视频搜索",
	 language227:"主播搜索",
	 language228:"与我私聊",
	 language229:"全球榜",
	 language230:"以",
	 language231:"传送信息",
	 language232:"所有",
	 language233:"获得",
	 language234:"使用",
	 language235:"购买",
	 
	},
	{
		// 登录部份-----------繁体中文
			 language1:"登入Cat",
			 language2:"請填寫正確格式",
			 language3:"下壹步",
			 language4:"將向您發送 One Click 登錄的驗證郵件",
			 language5:"驗證碼已發送",
			 language6:"已發送到",
			 language7:"請確認妳的電子信箱，並輸入六位數代碼！",
			 language8:"6位數代碼！",
			 language9:"若確認未收到信，請檢查垃圾信件或 在1:57 之後重新發送驗證電子郵件",
			 language10:"電子郵件驗證失敗",
			 language11:"若確認未收到信，請檢查垃圾信件或",
			 language12:"重新發送驗證信",
			 language13:"若確認未收到信，請檢查垃圾信件或 在1:57 之後重新發送驗證電子郵件",
			 language14:"歡迎來到亞洲最大的私密成人平臺 我們能給妳的以壹切叫做愛",
			 language15:"使用電子郵件登入/註冊",
			 language16:"其他登錄方法",
			 language17:"註冊/登入即代表妳年滿18歲並同意",
			 language18:"電子郵件",
			 language19:"將向您發送 One Click 登錄的驗證郵件",
			 language20:"請輸入手機號",
			 language21:"驗證碼將傳送到妳的手機",
			 language22:"您的電話號碼",
			 language23:"接收驗證碼",
			 language24:"選擇國家",
			 language25:"搜索",
			 language26:"號碼格式不符",
			 language27:"輸入驗證碼",
			 language28:"已傳送短信驗證碼到",
			 language29:"17秒",
			 language30:"修改手機號",
			 language31:"無效驗證碼",
			 
			 // 購買金幣部分
			 language32:"購買金幣",
			 language33:"購買包月VIP可享專屬服務",
			 language34:"詳情",
			 language35:"選擇貨幣",
			 language36:"包月",
			 language37:"特權壹",
			 language38:"免費獲得XXXXXX金幣",
			 language39:"特權二",
			 language40:"免費獲得XXXXXX金幣",
			 language41:"我要包月",
			 language42:"說明",
			 language43:"包月vip服務聲明",
			 language44:"付款:用戶確認購買綁定付款方式",
			 language45:"包月vip服務聲明  付款：用戶確認購買綁定付款方式  取消包月：如需取消包月，請在當前包月周期到期前24小時以 前，手動取消 個人中心-設置-付款方式綁定中取消,到期前24小時以內取消，將會收取包月費用。",
			 language46:"包月:包月周期前24小時內進行扣款,扣款成功後包月周期順延壹個包月周期。",
			 language47:"我要包月",
			 
			 language48:"首頁",
			 language49:"解鎖",
			 language50:"更多",
			 language51:"總排行榜",
			 language52:"解鎖榜",
			 language53:"聊天榜",
			 language54:"禮物榜",
			 language55:"搜索",
			 language56:"群發影片",
			 language57:"標簽",
			 language58:"Swagger",
			 language59:"熱門搜索",
			 language60:"最近",
			 language61:"粉絲推薦",
			 language62:"關註中",
			 language63:"粉絲數",
			 language64:"編輯",
			 language65:"已買商品",
			 language66:"8 貼文",
			 language67:"保存",
			 language68:"用戶名",
			 language69:"用戶說明",
			 language70:"檔案信息編輯",
			 language71:"關註",
			 language72:"在線",
			 language73:"熱門",
			 language74:"全球榜",
			 language75:"送禮",
			 language76:"聊天",
			 language77:"大家都在看",
			 language78:"解鎖",
			 language79:"新帖子",
			 language80:"性感",
			 language81:"則帖子",
			 language82:"所有信息",
			 language83:"剩余47小時",
			 language84:"取消",
			 language85:"免費",
			 language86:"商品管理",
			 language87:"收益管理",
			 language88:"已過期",
			 language89:"未審核",
			 language90:"刪除",
			 language91:"編輯",
			 language93:"上傳作品",
			 language94:"名稱",
			 language95:"價格",
			 language96:"上傳",
			 language97:"圖片",
			 language98:"時效",
			 language99:"提交",
			 language100:"收益管理",
			 language101:"私訊",
			 language102:"購買了妳的視頻",
			 language103:"給妳發了壹條私訊",
			 language104:"購買金幣",
			 language105:"信用卡支付",
			 language106:"您的卡片資料完全由合作金流進行加密處理；Cat不會保留完整的卡號信息。",
			 language107:"信用卡支付",
			 language108:"超商",
			 language109:"ibon便利生活站",
			 language110:"全家FAMIPORT",
			 language111:"ATM",
			 language112:"信用卡支付",
			 language113:"24小時",
			 language114:"7日",
			 language115:"30日",
			 language116:"每小時更新壹次",
			 language117:"每日更新壹次",
			 language118:"設定",
			 language119:"個人",
			 language120:"探索頁喜好",
			 language121:"女性",
			 language122:"已連結賬號",
			 language123:"封鎖名單",
			 language124:"刪除賬號",
			 language125:"錢包",
			 language126:"日誌",
			 language127:"支付方式",
			 language128:"我的電子收據",
			 language129:"購買金幣",
			 language130:"關於",
			 language131:"語言",
			 language132:"簡體中文",
			 language133:"繁體中文",
			 language134:"英語",
			 language135:"泰文",
			 language136:"男性",
			 language137:"全部",
			 language138:"常見問題",
			 language139:"聯系客服",
			 language140:"系統問題反饋",
			 language141:"免費下載 catr 應用程序",
			 language142:"更多",
			 language143:"退出",
			 language144:"我的電子收據",
			 language145:"捐贈發票",
			 language146:"電子收據",
			 language147:"探索頁喜好",
			 language148:"已連結賬號",
			 language149:"電子郵件",
			 language150:"Google",
			 language151:"Facebook",
			 language152:"Twitter",
			 language153:"line",
			 language154:"電話號碼",
			 language155:"連結賬號",
			 language156:"日誌",
			 language157:"所有",
			 language158:"獲得金幣",
			 language159:"登錄獎勵",
			 language160:"用戶充值",
			 language161:"禮物贈送",
			 language162:"個人設定",
			 language163:"請輸入您的用戶名",
			 language164:"限20字元，使用者名稱僅可使用小寫字母、數字",
			 language165:"Oops!您的年齡無法承受這些刺激",
			 language166:"妳感興趣的對象是...",
			 language167:"可復選，若欲更改至設定頁改變設定",
			 language168:"同意接收Cat的最新消息",
			 language169:"完成",
			 language170:"刪除賬號",
			 language171:"如果您想要刪除Cat賬號，請輸入賬號用戶名確認正確。刪除程序壹旦 開始，您將無法重啟賬號或取過去加到賬號的任何內容或資料。",
			 language172:"請輸入您的用戶名稱",
			 language173:"確認",
			 
			 //聊天
			 language174:"選擇朋友",
			 language175:"搜索",
			 language176:"我的朋友",
			 language177:"聊天",
			 language178:"建立聊天室",
			 language179:"跟對方說聲嗨！ 開始妳們的 1 對 1 聊天",
			 language180:"以3500 傳送信息",
			 language181:"拍照",
			 language182:"上傳",
			 language183:"作品列表",
			 language184:"應援",
			 language185:"情趣用品",
			 language186:"角色扮演",
			 language187:"生日快樂",
			 language188:"漂亮寶貝",
			 language189:"封鎖名單",
			 language191:"解除封鎖",
			 language192:"關於我",
			 language193:"106字",
			 language194:"作品列表",
			 language195:"取消",
			 language196:"推播通知",
			 language197:"私訊通知",
		
			 language198:"登錄/註冊",
			 language199:"條款",
			 language200:"在",
			 language201:"之後重新發送驗證電子郵件",
			 language202:"金幣",
			 language203:"視頻",
			 language204:"選擇上傳",
			 language205:"小時",
			 language206:"標簽前需要加#號區分",
			 language207:"剩余",
			 language208:"小時",
			 language209:"分鐘",
			 language210:"秒",
			 language211:"拉黑",
			 language212:"跟對方說聲嗨！",
			 language213:"開始妳們的 1 對 1 聊天",
			 language214:"客服LINE",
			 language215:"消費明細",
			 language216:"觀看",
			 language217:"綁定郵箱",
			 language218:"賬號不能為空",
			 language219:"可以註冊",
			 language220:"賬號已存在",
			 language221:"私訊價格",
			 language222:"合計收益",
			 language223:"熱門主播",
			 language224:"的限時動態",
			 language225:"相機",
			 language226:"視頻搜索",
			 language227:"主播搜索",
			 language228:"與我私聊",	
			 language229:"全球榜",
			 language230:"以",
			 language231:"傳送信息",
			 language232:"所有",
			 language233:"獲得",
			 language234:"使用",
			 language235:"購買",
	},
	{
		// 登录部份-----------英文
			 language1:"Login Cat",
		 	 language2:"Please write the correct format",
		 	 language3:"Next step",
		 	 language4:"Will send you a verification email for One Click login",
		 	 language5:"Verification code has sent",
		 	 language6:"Already sent to",
		 	 language7:"Please check your email and enter the six-digital code！",
		 	 language8:"six-digital code！",
		 	 language9:"If you do not receive the e-mail, please check the spam or resend the verification email after 1:57",
		 	 language10:"Email verification failed",
		 	 language11:"If you do not receive the email, please check the spam or",
		 	 language12:"Resend verification email",
		 	 language13:"If you do not receive the email, please check the spam or resend the verification email after 1:57",
		 	 language14:"Welcome to the largest private adult platform in Asia. We can give you everything called love.",
		 	 language15:"Login/register by using email",
		 	 language16:"Other login methods",
		 	 language17:"Register/login shows you are at least 18 years old and agree",
		 	 language18:"E-mail",
		 	 language19:"Will send you a verification email for One Click login ",
		 	 language20:"Please enter the phone number",
		 	 language21:"The verification code will be sent to your phone",
		 	 language22:"Your phone number",
		 	 language23:"Receive verification code",
		 	 language24:"Select country",
		 	 language25:"Search",
		 	 language26:"Number format does not match",
		 	 language27:"Enter verification code",
		 	 language28:"SMS verification code has been sent to +18565248951",
		 	 language29:"17 seconds",
		 	 language30:"Modify phone number",
		 	 language31:"Invalid verification code",
		 	 
		 	 // 购买金币部分
		 	 language32:"Buy cions",
		 	 language33:"buy monthly VIP to enjoy private services",
		 	 language34:"more",
		 	 language35:"Select currency",
		 	 language36:"Monthly VIP",
		 	 language37:"Privilege one",
		 	 language38:"Get XXXXXX coins for free",
		 	 language39:"Privilege two",
		 	 language40:"Get XXXXXX coins for free",
		 	 language41:"I want buy monthly VIP ",
		 	 language42:"Description",
		 	 language43:"Monthly VIP Service Statement",
		 	 language44:"Payment: User confirms purchase and bind payment method",
		 	 language45:"if you want to cancel pay monthly, please cancel 24 hours ago before the due date with manual cancellation. Personal account-setting-cancel binding of the payment method, please cancel 24 hours ago before the due date, or you will be charged monthly fee.",
		 	 language46:"Monthly VIP: Monthly VIP will be charged within 24 hours before it expires. After charge successfully, the monthly VIP will be extended to next month。",
		 	 language47:"I want buy monthly VIP",
		 	 
		 	 language48:"Homepage",
		 	 language49:"Unlock",
		 	 language50:"More",
		 	 language51:"Total",
		 	 language52:"Unlock top",
		 	 language53:"Chat top",
		 	 language54:"Gift top",
		 	 language55:"Search",
		 	 language56:"Mass videos",
		 	 language57:"Label",
		 	 language58:"Swagger",
		 	 language59:"hotting search",
		 	 language60:"Recent",
		 	 language61:"Fans recommend",
		 	 language62:"Following",
		 	 language63:"fans",
		 	 language64:"Edit",
		 	 language65:"Purchased goods",
		 	 language66:"8 post",
		 	 language67:"Save",
		 	 language68:"Username",
		 	 language69:"User description",
		 	 language70:"information edit",
		 	 language71:"Follow",
		 	 language72:"Online",
		 	 language73:"Hot",
		 	 language74:"Global top",
		 	 language75:"Send gift",
		 	 language76:"Chat",
		 	 language77:"Everyone is watching",
		 	 language78:"Unlock",
		 	 language79:"New post",
		 	 language80:"Sexy",
		 	 language81:"Post",
		 	 language82:"All information",
		 	 language83:"47 hours remaining",
		 	 language84:"Cancle",
		 	 language85:"Free",
		 	 language86:"goods management",
		 	 language87:"Income management",
		 	 language88:"Expired",
		 	 language89:"Unreviewed",
		 	 language90:"Delete",
		 	 language91:"Edit",
		 	 language93:"Upload video",
		 	 language94:"Name",
		 	 language95:"Price",
		 	 language96:"Upload",
		 	 language97:"image",
		 	 language98:"Timeliness",
		 	 language99:"Submit",
		 	 language100:"Income management",
		 	 language101:"Private message",
		 	 language102:"Purchased your video",
		 	 language103:"Sent a private message to you",
		 	 language104:"buy coins",
		 	 language105:"Pay by credit card",
		 	 language106:"Your card data is completely encrypted by the cooperative stream; Cat does not retain the complete card number information.",
		 	 language107:"Pay by credit card",
		 	 language108:"Supermarket",
		 	 language109:"ibon convenient living station",
		 	 language110:"FAMIPORT",
		 	 language111:"ATM",
		 	 language112:"Pay by credit card",
		 	 language113:"24hours",
		 	 language114:"7days",
		 	 language115:"30days",
		 	 language116:"Update every hour",
		 	 language117:"Update every day",
		 	 language118:"Setting",
		 	 language119:"personal",
		 	 language120:"Explore page preferences",
		 	 language121:"Female",
		 	 language122:"Linked with account",
		 	 language123:"Block list",
		 	 language124:"Delete account",
		 	 language125:"Wallet",
		 	 language126:"journal",
		 	 language127:"Payment method",
		 	 language128:"My electronic receipt",
		 	 language129:"buy coins",
		 	 language130:"About",
		 	 language131:"Language",
		 	 language132:"Simplified Chinese",
		 	 language133:"Traditional Chinese",
		 	 language134:"English ",
		 	 language135:"Thai ",
		 	 language136:"Male",
		 	 language137:"All",
		 	 language138:"Common problem",
		 	 language139:"Contact Customer Service",
		 	 language140:"System problem feedback",
		 	 language141:"Free download Cat application",
		 	 language142:"More",
		 	 language143:"logout",
		 	 language144:"My electronic receipt",
		 	 language145:"Donate receipt",
		 	 language146:"Electronic receipt",
		 	 language147:"Explore page preferences",
		 	 language148:"Linked with account",
		 	 language149:"E-mail",
		 	 language150:"Google",
		 	 language151:"Facebook",
		 	 language152:"Twitter",
		 	 language153:"line",
		 	 language154:"Phone number",
		 	 language155:"Link account",
		 	 language156:"journal",
		 	 language157:"All",
		 	 language158:"Get coins",
		 	 language159:"Login reward",
		 	 language160:"User recharge",
		 	 language161:"Send gift",
		 	 language162:"Personal setting",
		 	 language163:"Please enter your username",
		 	 language164:"Limited to 20 words, username can only use lowercase letters, numbers",
		 	 language165:"Oops! Your age cannot login",
		 	 language166:"what you interested in is...",
		 	 language167:"Multi-choice,if want to change, go to “setting”",
		 	 language168:"Agree to receive the latest news from Cat",
		 	 language169:"Complete",
		 	 language170:"Delete account",
		 	 language171:"If you want to delete the Cat account, please enter the correct account username. Once the removal process begins, you will not be able to restart your account to get any content or information that was added to your account before.",
		 	 language172:"Please enter your username",
		 	 language173:"Confirm",
		 	 
		 	 //聊天
		 	 language174:"Choose friends",
		 	 language175:"search",
		 	 language176:"My friend",
		 	 language177:"Chat",
		 	 language178:"Build a chat room",
		 	 language179:"Say “Hi” to other party! Start your 1V1 chat",
		 	 language180:"Use 3500 to send message",
		 	 language181:"Take photo",
		 	 language182:"Upload",
		 	 language183:"work list",
		 	 language184:"Support",
		 	 language185:"Sex toys",
		 	 language186:"Cosplay",
		 	 language187:"Happy Birthday",
		 	 language188:"Pretty Baby",
		 	 language189:"Block list",
		 	 language191:"Unlock ban",
		 	 language192:"About me",
		 	 language193:"106 words",
		 	 language194:"work list",
		 	 language195:"Cancel",
		 	 language196:" notification",
		 	 language197:"Private message notification",
		 
			 language198:"Login/ register",
		 	 language199:"Item",
		 	 language200:"In",
		 	 language201:"Then resend the verification email",
		 	 language202:"coins",
		 	 language203:"Video",
		 	 language204:"Select to upload",
		 	 language205:"Hour",
		 	 language206:"Need to add # in the label to distinguish",
		 	 language207:"Remaining",
		 	 language208:"Hour",
		 	 language209:"Minute",
		 	 language210:"Second",
		 	 language211:"Block",
		 	 language212:"Say “Hi” to others！",
		 	 language213:"Start your 1V1 chat",
		 	 language214:"Customer service LINE",
		 	 language215:"Consumption details",
		 	 language216:"Watch",
		 	 language217:"Bind mailbox",
		 	 language218:"Account cannot be empty",
		 	 language219:" Register is available",
		 	 language220:"Account already existed",
		 	 language221:"Private message price",
		 	 language222:"Total income",
		 	 language223:"Top anchors",
		 	 language224:"Time-limited moments",
		 	 language225:"Camera",
		 	 language226:"Video search",
		 	 language227:"Anchor search",
		 	 language228:"chat with me privately",
			 language229:"Global Leaderboard",
			 language230:"Use",
			 language231:"to send message",
			 language232:"All",
			 language233:"Get",
			 language234:"Use",
			 language235:"Buy",
	},	
	{
		// ส่วนของการลงชื่อเข้าใช้-------ภาษาอังกฤษ
		 language1:"ลงชื่อเข้าใช้ Cat",
			 language2:"กรุณากรอกแบบฟอร์มที่ถูกต้อง",
			 language3:"ถัดไป",
			 language4:"จะส่งอีเมลยืนยันการลงชื่อแบบ One Click ไปให้คุณ ",
			 language5:"ส่งรหัสยืนยันแล้ว",
			 language6:"ส่งไปยัง",
			 language7:"กรุณายืนยันอีเมลของคุณและใส่รหัสตัวเลข 6 หลัก！",
			 language8:"รหัสตัวเลข 6 หลัก！",
			 language9:" หากคุณแน่ใจแล้วว่าไม่ได้รับอีเมล กรุณาตรวจสอบที่อีเมลขยะหรือหลังจาก 1.57 นาที จะส่งอีเมลยืนยันอีกครั้ง",
			 language10:"การส่งอีเมลยืนยันล้มเหลว",
			 language11:" หากคุณแน่ใจแล้วว่าไม่ได้รับอีเมล กรุณาตรวจสอบที่อีเมลขยะหรือ ",
			 language12:"ส่งอีเมลยืนยันอีกครั้ง",
			 language13:" หากคุณแน่ใจแล้วว่าไม่ได้รับอีเมล กรุณาตรวจสอบที่อีเมลขยะหรือหลังจาก 1.57 นาที จะส่งอีเมลยืนยันอีกครั้ง",
			 language14:" ยินดีต้อนรับเข้าสู่แอปพลิเคชั่นส่วนตัวของผู้ใหญ่ที่ใหญ่ที่สุดในเอเชีย สิ่งที่เราให้คุณได้ทั้งหมด เรียกว่าความรัก",
			 language15:"ใช้อีเมลลงชื่อเข้าใช้/ลงทะเบียน",
			 language16:"วิธีการลงชื่อเข้าใช้อื่นๆ",
			 language17:"ลงะเบียน/ลงชื่อเข้าใช้ แสดงว่าคุณอายุครบ 18 ปีและยินยอม",
			 language18:"อีเมล",
			 language19:"จะส่งอีเมลยืนยันการลงชื่อแบบ One Click ไปให้คุณ ",
			 language20:"กรุณาใส่เบอร์มือถือ",
			 language21:"จะส่งรหัสยืนยันไปยังมือถือของคุณ",
			 language22:"เบอร์โทรศัพท์ของคุณ",
			 language23:"รับรหัสยืนยัน",
			 language24:"เลือกประเทศ",
			 language25:"ค้นหา",
			 language26:"รูปแบบหมายเลขไม่ถูกต้อง",
			 language27:"ใส่รหัสยืนยัน",
			 language28:"ส่งข้อความรหัสยืนยันไปยัง +18565248951 แล้ว",
			 language29:"17 วินาที",
			 language30:"แก้ไขเบอร์มือถือ",
			 language31:"รหัสยืนยันหมดอายุ",
			 
			 // ส่วนของการซื้อเหรียญ
			 language32:"ซื้อเหรียญ",
			 language33:"เหมาซื้อVIPรายเดือนสามารถได้สิทธิ์ใช้บริการพิเศษ",
			 language34:"รายละเอียด",
			 language35:"เลือกสกุลเงิน",
			 language36:"รายเดือน",
			 language37:"สิทธิประโยชน์ 1",
			 language38:"ได้รับXXXXXXเหรียญฟรี",
			 language39:"สิทธิประโยชน์ 2",
			 language40:"ได้รับXXXXXXเหรียญฟรี",
			 language41:"ฉันอยากได้แบบรายเดือน",
			 language42:"อธิบาย",
			 language43:"รายละเอียดบริการvip รายเดือน ",
			 language44:"การชำระเงิน : ผู้ใช้ยืนยันวิธีการชำระเงินแบบผูกมัด",
			 language45:" รายละเอียดการชำระเงินบริการ VIP รายเดือน: ผู้ใช้ยืนยันวิธีการชำระเงินที่มีผลผูกมัด ยกเลิกการสมัครสมาชิกรายเดือน: หากคุณต้องการยกเลิกการสมัครสมาชิกรายเดือนโปรดยกเลิกก่อนหมดอายุ 24 ชม.  ยกเลิกด้วยตนเอง ศูนย์ส่วนบุคคล- ตั้งค่า- ยกเลิกในวิธีการชำระเงินแบบผูกมัดภายใน 24 ชั่วโมงจะต้องเสียค่าธรรมเนียมรายเดือน ",
			 language46: "วันจันทร์: การหักเงินจะทำภายใน 24 ชั่วโมงก่อนระยะเวลาการสมัครสมาชิกรายเดือนหลังจากการหักที่ประสบความสำเร็จระยะเวลาการสมัครสมาชิกรายเดือนจะถูกขยายโดยหนึ่งเดือน",
			 language47:"ฉันอยากได้แบบรายเดือน",
			 
			 language48:"หน้าแรก",
			 language49:"ปลดล็อค ",
			 language50:"เพิ่มเติม",
			 language51:"ชาร์ทการจัดอันดับทั้งหมด",
			 language52:"ชาร์ทปลดล็อค",
			 language53:"ชาร์ทสนทนา",
			 language54:"ชาร์ทของขวัญ",
			 language55:"ค้นหา",
			 language56:"วิดีโอที่ส่งในกลุ่ม",
			 language57:"ฉลาก",
			 language58:"Swagger",
			 language59:"คำค้นหาที่เป็นที่นิยม",
			 language60:"ช่วงนี้",
			 language61:"แฟนคลับแนะนำ",
			 language62:"กำลังติดตาม",
			 language63:"จำนวนแฟนคลับ",
			 language64:"แก้ไข",
			 language65:"ซื้อสินค้าแล้ว",
			 language66:" 8 โพสต์",
			 language67:"บันทึก",
			 language68:"ชื่อผู้ใช้",
			 language69:"คำอธิบายผู้ใช้",
			 language70:"แก้ไขข้อมูลไฟล์",
			 language71:"ติดตาม",
			 language72:"ออนไลน์",
			 language73:"ฮอตฮิต",
			 language74:"ชาร์ททั่วโลก",
			 language75:"ส่งของขวัญ",
			 language76:"สนทนา",
			 language77:"ทุกคนกำลังดู",
			 language78:"ปลดล็อค",
			 language79:"สติ๊กเกอร์ใหม่",
			 language80:"เซ็กซี่",
			 language81:"โพสต์",
			 language82:"ข้อความทั้งหมด",
			 language83:"เหลืออีก 47 วินาที",
			 language84:"ยกเลิก",
			 language85:"ฟรี",
			 language86:"การจัดการสินค้า",
			 language87:"การจัดการกำไล",
			 language88:"หมดอายุแล้ว",
			 language89:"ยังไม่ผ่าน",
			 language90:"ลบ",
			 language91:"แก้ไข",
			 language93:"อัพโหลดผลงาน",
			 language94:"ชื่อ",
			 language95:"ราคา",
			 language96:"อัพโหลด",
			 language97:"รูปภาพ",
			 language98:"กำหนดเวลา ",
			 language99:"ส่ง",
			 language100:"การจัดการกำไล",
			 language101:"ข้อความส่วนตัว",
			 language102:"ซื้อวิดีโอของคุณแล้ว",
			 language103:"ส่งจ้อความส่วนตัวให้คุณ 1 ข้อความ",
			 language104:"ซื้อเหรียญ",
			 language105:"ชำระโดยใช้บัตรเครดิต",
			 language106:" ข้อมูลบัตรของคุณจะถูกเก็บเป็นความลับอย่างดีด้วยความร่วมมือของทางการเงิน Cat จะไม่เก็บข้อมูลบัตรทั้งหมด",
			 language107:"ชำระโดยใช้บัตรเครดิต",
			 language108:"ซุปเปอร์มาร์เก็ต",
			 language109:"ibon สถานีชีวิตสะดวกสบาย",
			 language110:"FAMIPORT",
			 language111:"ATM",
			 language112:"ใช้บัตรเครดิตจ่าย",
			 language113:"24 ชม.",
			 language114:"7 วัน",
			 language115:"30 วัน",
			 language116:"ทุก ชม. อัพโหลด 1 ครั้ง",
			 language117:"ทุกวัน อัพโหลด 1 ครั้ง",
			 language118:"ตั้งค่า",
			 language119:"ส่วนตัว",
			 language120:"ค้นหาหน้าทีชอบ",
			 language121:"เพศหญิง",
			 language122:"เชื่อมต่อบัญชีแล้ว",
			 language123:"รายชื่อผู้ที่โดนบล็อค",
			 language124:"ลบ",
			 language125:"กระเป๋าเงิน",
			 language126:"บันทึกประจำวัน",
			 language127:"วิธีชำระเงิน",
			 language128:"ใบเสร็จอิเล็กทรอนิกส์ของฉัน",
			 language129:"ซื้อเหรียญ",
			 language130:"เกี่ยวกับ",
			 language131:"ภาษา",
			 language132:"จีนตัวย่อ",
			 language133:"จีนตัวเต็ม",
			 language134:"ภาษาอังกฤษ",
			 language135:"ภาษาไทย",
			 language136:"เพศชาย",
			 language137:"ทั้งหมด",
			 language138:"ปัญหาที่พบบ่อย",
			 language139:"ติดต่อเรา",
			 language140:"ฟีดแบ็คปัญหาระบบ",
			 language141:"โหลดแอป Cat ฟรี",
			 language142:"เพิ่มเติม",
			 language143:"ลงชื่อออก",
			 language144:"ใบเสร็จอิเล็กทรอนิกส์ของฉัน",
			 language145:"ใบเสร็จบริจาค",
			 language146:"ใบเสร็จอิเล็กทรอนิกส์",
			 language147:"ค้นหาหน้าที่ชอบ",
			 language148:"เชื่อมต่อบัญชีแล้ว",
			 language149:"อีเมล",
			 language150:"Google",
			 language151:"Facebook",
			 language152:"Twitter",
			 language153:"line",
			 language154:"เบอร์มือถือ",
			 language155:"เชื่อมต่อบัญชี",
			 language156:"บันทึกประจำวัน",
			 language157:"ทั้งหมด",
			 language158:"ได้รับเหรียญ",
			 language159:"ลงชื่อได้รางวัล",
			 language160:"ผู้ใช้เติมเงิน",
			 language161:"ส่งของขวัญฟรี",
			 language162:"ตั้งค่าด้วยตนเอง",
			 language163:"กรุณาใส่ชื่อผู้ใช้ของคุณ",
			 language164:"จำกัด 20 ตัว，ชื่อผู้ใช้สามารถใช้อักษรตัวพิมพ์เล็กและตัวเลขเท่านั้น",
			 language165:"Oops!อายุของคุณไม่สามารถรับชมสิ่งเร้าเหล่านี้ได้",
			 language166:"เพศตรงข้ามที่คุณสนใจคือ...",
			 language167:"เลือกใหม่ได้，หากอยากแก้ให้ไปที่หน้าตั้งค่าแล้วเปลี่ยนการตั้งค่า",
			 language168:"ตกลงที่จะรับข่าวสารล่าสุดจาก Cat ",
			 language169:"สำเร็จ",
			 language170:"ลบบัญชี",
			 language171:"หากคุณต้องการลบบัญชี Cat โปรดป้อนชื่อผู้ใช้บัญชีเพื่อยืนยัน เมื่อกระบวนการลบเริ่มต้นขึ้นคุณจะไม่สามารถรีสตาร์ทบัญชีของคุณหรือดึงเนื้อหาหรือเนื้อหาใด ๆในอดีต ที่เพิ่มเข้ามาในบัญชีของคุณได้",
			 language172:"กรุณาใส่ชื่อบัญชีของคุณ",
			 language173:"ตกลง",
			 
			 //สนทนา
			 language174:"เลือกเพื่อน",
			 language175:"ค้นหา",
			 language176:"เพื่อนของฉัน",
			 language177:"สนทนา",
			 language178:"สร้างห้องแชท",
			 language179:"เซย์ไฮย์กับเขา！ เริ่มแชทแบบตัวต่อตัว",
			 language180:" ใช้ 3500 ส่งต่อข้อความ",
			 language181:"ถ่ายรูป",
			 language182:"อัพโหลด",
			 language183:"รายชื่อผลงาน",
			 language184:"สนับสนุน",
			 language185:"เซ็กส์ทอย",
			 language186:"แสดงละคร",
			 language187:"สุขสันต์วันเกิด",
			 language188:"เบบี้สุดสวย",
			 language189:"รายชื่อคนโดนบล็อค",
			 language191:"ปลดล็อค",
			 language192:"เกี่ยวกับฉัน",
			 language193:"106ตัว",
			 language194:"รายชื่อผลงาน",
			 language195:"ยกเลิก",
			 language196:"ประกาศแนะนำไลฟ์",
			 language197:"ประกาศข้อความส่วนตัว",
		
			 language198:"ลงชื่อเข้าใช้/ลงทะเบียน",
			 language199:"เงื่อนไข",
			 language200:"ที่",
			 language201:"หลังจาก...จะส่งอีดมลยืนยันใหม่",
			 language202:"เหรียญ",
			 language203:"วิดีโอ",
			 language204:"เลือกอัพโหลด",
			 language205:"ชม.",
			 language206:"ก่อนฉลากต้องเพิ่ม#เพื่อแยก",
			 language207:"เหลือ",
			 language208:"ชม.",
			 language209:"นาที",
			 language210:"วินาที",
			 language211:"แบล็คเมล",
			 language212:"เซย์ไฮย์กับเขา！",
			 language213:"เริ่มแชทแบบตัวต่อตัว",
			 language214:"อีเมลของเรา ",
			 language215:"รายละเอียดค่าใช้จ่าย",
			 language216:"ดู",
			 language217:"เชื่อมอีเมล",
			 language218:"ชื่อบัญชีเว้นไม่ได้",
			 language219:"ลงทะเบียนได้",
			 language220:"บัญชีนี้มีอยู่แล้ว",
			 language221:"ราคาข้อความส่วนตัว",
			 language222:"กำไลทั้งหมด",
			 language223:"วีเจดัง",
			 language224:"สถานะจำกัดเวลา",
			 language225:"กล้อง",
			 language226:"ค้นหาวิดีโอ",
			 language227:"ค้นหาวีเจ",
			 language228:"คุยกับฉัน",
			 language229:"ชาร์ตทั่วโลก",
			 language230:"ใช้",
			 language231:"ส่งต่อข้อความ",
			 language232:"ทั้งหมด",
			 language233:"ได้รับเหรียญ",
			 language234:"ใช้",
			 language235:"ซื้อเหรียญ",
	}
]

export default
{
  language,//tag数组 test
}